---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'CloudWatch Alarm to Slack'
Parameters:
  Threshold:
    Description: 'Alarm, if your monthly estimated charges are higher'
    Default: 1
    Type: Number
  WebhookURL:
    Description: 'Slack incoming webhook URL'
    Type: String
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'handler.event'
      Runtime: 'nodejs14.x'
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookURL
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref Topic
  Alarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - !Ref Topic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: 'AWS/Billing'
      Period: 86400
      Statistic: Maximum
      Threshold: !Ref Threshold
